# Generated by Django 3.1.3 on 2023-04-19 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grado', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'grado',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=45, unique=True, verbose_name='Apodo del usuario')),
                ('email', models.CharField(max_length=45, verbose_name='Correo del usuario')),
                ('nombres', models.CharField(max_length=45, verbose_name='Nombres del usuario')),
                ('apellidos', models.CharField(max_length=45, verbose_name='Apellidos del usuario')),
                ('documento', models.CharField(max_length=45, verbose_name='Documento del usuario')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=45)),
                ('codigo_grupo', models.CharField(max_length=45)),
                ('grado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Math_children.grado')),
                ('usu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
    ]
